version: '3.7'

services: 

  drone: 
    container_name: drone
    image: drone
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - 4021:4021
    networks:
      - server-network
    environment:
      app_name: drone
      KAFKA_SERVER_URL: ${SERVER_URL} 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped


  
networks:
  server-network:
    driver: bridge    


